services:
  amazon-photos-sync:
    build: .
    container_name: amazon-photos-sync
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - WATCH_DIR=/watch_dir
      - DRY_RUN=false
      - SYNC_EXTENSIONS=heic jpg jpeg png
      - SYNC_RECURSIVE=true
      - AMAZON_EMAIL=b.kreitz@mail.de
      - AMAZON_PASSWORD=Wb2010eYH!an
    volumes:
      # Mount point for local photos directory to sync (Change this to your actual photos directory path)
      - ./sync_test_folder:/watch_dir
      # Mount point for config persistence (cookies, sync cache database)
      - ./config:/config
